server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ecomdb}
    username: ${DB_USER:ashish}
    password: ${DB_PASSWORD:password123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:defaultDevSecretMustBeAtLeast32CharactersLongForHS256!}
  expiration: ${JWT_EXPIRATION:86400000}
