server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: ashish
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: products
